force-app/main/default/objects/StageTracker__c/StageTracker__c.object-meta.xml
<CustomObject>
    <description>Used to hold Stage/Status duration information for the Lead/Case/Opportunity object</description>
    <label>Stage Tracker</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stages Tracked</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StageTracker__c/fields/Cumulated_Days__c.field-meta.xml
<CustomField>
    <fullName>Cumulated_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number field used to store the days cumulated for this field/object combo. This field is needed for when a stage/status field get switched forward and then backwards to the same stage. This field keeps the previous total time and adds it into the formula for total time in stage</description>
    <inlineHelpText>In Days</inlineHelpText>
    <label>Cumulated Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StageTracker__c/fields/Inactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Date__c</fullName>
    <description>The date when this field/object combo stopped being active. Note if this field is null the end date is calculated as NOW()</description>
    <label>Inactive Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/StageTracker__c/fields/Last_Active_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Active_Date__c</fullName>
    <defaultValue>Now()</defaultValue>
    <description>The date this field was switched active for this field/object combo</description>
    <label>Last Active Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/StageTracker__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Lead this Stage Tracker is Related to</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Status Changes Tracked</relationshipLabel>
    <relationshipName>Stages_Tracked</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StageTracker__c/fields/Times_Moved_Out__c.field-meta.xml
<CustomField>
    <fullName>Times_Moved_Out__c</fullName>
    <description>The Number of times this stage has been switched to another stage</description>
    <label>Times Moved Out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StageTracker__c/fields/Times_Moved_To__c.field-meta.xml
<CustomField>
    <fullName>Times_Moved_To__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of times this stage has been selected</description>
    <label>Times Moved To</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StageTracker__c/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <description>Case Status Tracker</description>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/StageTracker__c/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>Lead Status Tracker</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/StageTracker__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <description>Opportunity Stage Tracker</description>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/CK_StageTrackerTest.cls
/******************************************************************************
Author:Ryan O'Sullivan
Company:CloudKettle
Description:Test class for the Stage Tracker managment functionaility

History:
 Date:2018-05-29
 By:Ryan O'Sullivan
 Action:Created
******************************************************************************/
@isTest
private class CK_StageTrackerTest {

	@TestSetup
	static void setupMethod(){
		// Create 10 test leads
		Lead[] testLeads = CK_TestFactory.createLeads(10);
		Database.SaveResult[] leadRes = Database.insert(testLeads,false);
		for(Database.SaveResult res : leadRes){
			System.assert(res.isSuccess());
		}

		// Create 1 account
		Account[] testAccount = CK_TestFactory.createAccounts(1);
		Database.SaveResult[] accountRes = Database.insert(testAccount,false);
		for(Database.SaveResult res : accountRes){
			System.assert(res.isSuccess());
		}

		// Create 10 Opps
		Opportunity[] testOpps = CK_TestFactory.createOpportunities(10,accountRes[0].getId());
		Database.SaveResult[] oppRes = Database.insert(testOpps,false);
		for(Database.SaveResult res : oppRes){
			System.assert(res.isSuccess());
		}

		// Create 10 Cases
		Case[] testCases = CK_TestFactory.createCases(10,accountRes[0].getId());
		Database.SaveResult[] caseRes = Database.insert(testCases, false);
		for(Database.SaveResult res : caseRes){
			System.assert(res.isSuccess());
		}
	}

	@isTest static void LeadUpdate() {
		Map<Id,Lead> testLeads = new Map<Id,Lead>([Select id,status from Lead]);
		Map<Id,StageTracker__c> leadTrackers = new Map<Id,StageTracker__c> ([Select id FROM StageTracker__c Where lead__c in: testLeads.keySet()]);

		Integer startingTrackerSize = leadTrackers.size();
		String startingStatus = testLeads.values()[0].status;

		System.assertEquals(testleads.size(), startingTrackerSize);

		Test.startTest();

		// Change status to a random new one
		for(Lead oLead : testLeads.values()){
			oLead.status = Ck_TestFactory.getRandomPicklistValue(Lead.sObjectType, 'Status', oLead.status);
			testLeads.put(oLead.id,oLead);
		}

		Database.SaveResult[] leadUpdate = Database.update(testLeads.values(),false);
		for(Database.SaveResult res : leadUpdate){
			System.assert(res.isSuccess());
		}

		leadTrackers = new Map<Id,StageTracker__c>([Select id ,name,Last_Active_date__c, Inactive_Date__c ,Times_Moved_Out__c, Times_Moved_To__c,Lead__c FROM StageTracker__c WHERE lead__c in: testleads.keySet()]);
		System.assertNotEquals(startingTrackerSize, leadTrackers.size());

		for(StageTracker__c tracker : leadTrackers.values()){
			Lead relatedLead = testLeads.get(tracker.lead__c);
			if(relatedLead.status != tracker.name){
				// Tracker for state 0
				System.assert(tracker.Times_Moved_Out__c > 0);
				System.assert(tracker.Inactive_Date__c != null);
				tracker.Last_Active_date__c = DateTime.now().addDays(-1);
				leadTrackers.put(tracker.id,tracker);
			} else {
				// Tracker for new state
				System.assert(tracker.Times_Moved_Out__c == 0);
				System.assert(tracker.Inactive_Date__c == null);
			}
		}

		// Update dates on trackers
		Database.SaveResult[] trackerRes = Database.update(leadTrackers.values(),false);
		for(Database.SaveResult res: trackerRes){
			System.assert(res.isSuccess());
		}

		// Change status back to the old one
		for(Lead oLead : testLeads.values()){
			oLead.status = startingStatus;
			testLeads.put(oLead.id,oLead);
		}
		Database.SaveResult[] leadUpdate2 = Database.update(testLeads.values(),false);
		for(Database.SaveResult res : leadUpdate2){
			System.assert(res.isSuccess());
		}

		leadTrackers = new Map<Id,StageTracker__c>([Select id,Cumulated_Days__c,Inactive_Date__c ,Times_Moved_Out__c, Times_Moved_To__c,Lead__c FROM StageTracker__c WHERE lead__c in: testleads.keySet() AND name =: startingStatus]);
		System.assertEquals(startingTrackerSize,leadTrackers.size());
		for(StageTracker__c tracker : leadTrackers.values()){
			System.assert(tracker.Times_Moved_To__c == 2);
			System.assert(tracker.Inactive_Date__c == null);
			System.assertEquals(tracker.Cumulated_Days__c, 1);
		}

		Test.stopTest();
		
	}
	
	@isTest static void leadDeleteAndUndelete() {
		Map<Id,Lead> testLeads = new Map<Id,Lead>([Select id FROM Lead]);
		Integer countOfTrackers = [Select count() from StageTracker__c where lead__c in: testLeads.keySet()];

		Database.DeleteResult[] leadDelRes = Database.delete(testLeads.values(),false);
		for(Database.DeleteResult res : leadDelRes){
			System.assert(res.isSuccess());
		}

		Integer deletedCount = [Select count() from StageTracker__c where lead__c in: testLeads.keySet()];

		System.assertNotEquals(countOfTrackers,deletedCount);

		// Undelete
		Database.UndeleteResult[] leadUndelRes = Database.undelete(testLeads.values());
		for(Database.UndeleteResult res : leadUndelRes){
			System.assert(res.isSuccess());
		}

		Integer undeletedCount = [Select count() from StageTracker__c where Lead__c in: testLeads.keySet()];

		System.assertEquals(countOfTrackers,undeletedCount);
	}


}