force-app/main/default/objects/Account/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <label>ARR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <description>ARR. Created by CK Ext. 221</description>
    <inlineHelpText>Put 0 (if you dont know) but update this number as we gather more info from the prospect.</inlineHelpText>
    <label>ARR</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Implementation_Fee__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Fee__c</fullName>
    <description>Implementation Fee details. Created by CK Ext. 221</description>
    <label>Implementation Fee</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Partner Inquiry</fullName>
            </value>
            <value>
                <fullName>Sent to Reseller - MEP</fullName>
            </value>
            <value>
                <fullName>Product Feature Missing</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Need Provider Group</fullName>
            </value>
            <value>
                <fullName>Project Abandoned by Customer</fullName>
            </value>
            <value>
                <fullName>Competitor Strength</fullName>
            </value>
            <value>
                <fullName>Timeline</fullName>
            </value>
            <value>
                <fullName>Product Fit</fullName>
            </value>
            <value>
                <fullName>Internal Decision</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Company Size</fullName>
                <isActive>false</isActive>
                <label>Company Size</label>
            </value>
            <value>
                <fullName>Contract Changes</fullName>
                <isActive>false</isActive>
                <label>Contract Changes</label>
            </value>
            <value>
                <fullName>Disqualified Appointment</fullName>
                <isActive>false</isActive>
                <label>Disqualified Appointment</label>
            </value>
            <value>
                <fullName>International</fullName>
                <isActive>false</isActive>
                <label>International</label>
            </value>
            <value>
                <fullName>Price</fullName>
                <isActive>false</isActive>
                <label>Price</label>
            </value>
            <value>
                <fullName>Project cancelled</fullName>
                <isActive>false</isActive>
                <label>Project cancelled</label>
            </value>
            <value>
                <fullName>Reimbursement Issues</fullName>
                <isActive>false</isActive>
                <label>Reimbursement Issues</label>
            </value>
            <value>
                <fullName>Technology Constraints</fullName>
                <isActive>false</isActive>
                <label>Technology Constraints</label>
            </value>
            <value>
                <fullName>Timing 13+ months</fullName>
                <isActive>false</isActive>
                <label>Timing 13+ months</label>
            </value>
            <value>
                <fullName>Unresponsive</fullName>
                <isActive>false</isActive>
                <label>Unresponsive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Use_Case__c.field-meta.xml
<CustomField>
    <fullName>Use_Case__c</fullName>
    <label>Use Case</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Care</fullName>
            </value>
            <value>
                <fullName>Specialty Care</fullName>
            </value>
            <value>
                <fullName>ED Teletriage</fullName>
            </value>
            <value>
                <fullName>ED Telepsychiatry</fullName>
            </value>
            <value>
                <fullName>Provider to Provider Consultations</fullName>
            </value>
            <value>
                <fullName>Virtual Urgent Care</fullName>
            </value>
            <value>
                <fullName>Oncology Virtual Care</fullName>
            </value>
            <value>
                <fullName>Telestroke</fullName>
            </value>
            <value>
                <fullName>Behavioral Health</fullName>
            </value>
            <value>
                <fullName>Virtual Nursing</fullName>
            </value>
            <value>
                <fullName>Tele-ICU</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Correctional Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityControllerTest.cls
@isTest
public class OpportunityControllerTest {
    
      @testSetup static void testData(){
          
        Date dt = Date.today().addDays(+1);
          
        Account accs = new Account(Name='Test Account');
    	insert accs;
          
        Opportunity opps = new Opportunity(Name='Test',Amount=12,stageName='Discovery and Qualification',AccountId=accs.Id,LeadSource='Website',ARR__c=10,Use_Case__c='Primary Care',CloseDate=dt,Implementation_Fee__c=10);
        insert opps;
          
        Opportunity opps1 = new Opportunity(Name='Test1',Amount=12,stageName='Closed Won',AccountId=accs.Id,LeadSource='Website',ARR__c=10,Use_Case__c='Primary Care',CloseDate=dt,Implementation_Fee__c=10);
        insert opps1;
        
    }
    
     @isTest static void OpportunityControllerTrigger(){
        List<Account> accList = [Select id,Name from Account LIMIT 1];
        List<Opportunity> newoppLIst = [Select id,Name,Amount,stageName,AccountId,LeadSource,ARR__c,Use_Case__c,Implementation_Fee__c from Opportunity Where Name = 'Test'];
        newoppLIst[0].stageName = 'Closed Lost';
        newoppLIst[0].Loss_Reason__c = 'Competitor';
         
        Test.startTest();
        List<Database.SaveResult> result = Database.update(newoppLIst, false);
        Test.stopTest();
           /* System.assert(!result[0].isSuccess());
            System.assert(result[0].getErrors().size() > 0);
            System.assertEquals('Please select a value for eVisit Noted Differentiators',result[0].getErrors()[0].getMessage());
			*/
    }
    
    @isTest static void getStageNamesTest(){
        List<Opportunity> newoppLIst = [Select id,Name,Amount,stageName,AccountId,LeadSource,ARR__c,Implementation_Fee__c,Use_Case__c from Opportunity Where Name = 'Test'];
        List<Object> stageString = new List<Object>();
         stageString.add(newoppLIst[0].stageName+'='+newoppLIst[0].stageName);
         List<Object> oppObj = OpportunityController.getStageNames('Closed Won','Opportunity','StageName');
       	 System.assert(oppObj.size() > 0);
    }
    
    @isTest static void getRecordDetailsTest(){
        List<Opportunity> newoppLIst = [Select id,Name,Amount,stageName,AccountId,LeadSource,ARR__c,Implementation_Fee__c,Use_Case__c from Opportunity Where Name = 'Test'];
        String s = OpportunityController.getRecordDetails(newoppLIst[0].Id);
        System.assertEquals(s,'Discovery and Qualification');
    }

}