force-app/main/default/objects/Lead/fields/DefHC_Hospital_Name__c.field-meta.xml
<CustomField>
    <fullName>DefHC_Hospital_Name__c</fullName>
    <label>DHC Hospital Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DHC_EMR_Vendor_Ambulatory__c.field-meta.xml
<CustomField>
    <fullName>DHC_EMR_Vendor_Ambulatory__c</fullName>
    <label>DHC EMR Vendor Ambulatory</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DHC_EMR_Vendor_Inpatient__c.field-meta.xml
<CustomField>
    <fullName>DHC_EMR_Vendor_Inpatient__c</fullName>
    <label>DHC EMR Vendor Inpatient</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DHC_Net_Patient_Revenue__c.field-meta.xml
<CustomField>
    <fullName>DHC_Net_Patient_Revenue__c</fullName>
    <label>DHC Net Patient Revenue</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DHC_Network_ID__c.field-meta.xml
<CustomField>
    <fullName>DHC_Network_ID__c</fullName>
    <label>DHC Network ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DHC_Network_Name__c.field-meta.xml
<CustomField>
    <fullName>DHC_Network_Name__c</fullName>
    <label>DHC Network Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DHC_No_of_Beds__c.field-meta.xml
<CustomField>
    <fullName>DHC_No_of_Beds__c</fullName>
    <label>DHC # of Beds</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DHC_No_of_Discharges__c.field-meta.xml
<CustomField>
    <fullName>DHC_No_of_Discharges__c</fullName>
    <label>DHC # of Discharges</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DHC_of_No_Affiliated_Physicians__c.field-meta.xml
<CustomField>
    <fullName>DHC_of_No_Affiliated_Physicians__c</fullName>
    <label>DHC # of Affiliated Physicians</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DHC_Parent_Network_ID__c.field-meta.xml
<CustomField>
    <fullName>DHC_Parent_Network_ID__c</fullName>
    <label>DHC Parent Network ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DHC_Parent_Network_Name__c.field-meta.xml
<CustomField>
    <fullName>DHC_Parent_Network_Name__c</fullName>
    <label>DHC Parent Network Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DHC_Provider_Profile__c.field-meta.xml
<CustomField>
    <fullName>DHC_Provider_Profile__c</fullName>
    <label>DHC Provider Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DHC_Provider_Website__c.field-meta.xml
<CustomField>
    <fullName>DHC_Provider_Website__c</fullName>
    <label>DHC Provider Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Ultimate_Parent_Lead__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Parent Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Leads (Ultimate Parent Lead)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UploadLeadController.cls
public class UploadLeadController {
    
    public static void dele(){
        List<Lead> leadList = [Select id,name from Lead];
        delete leadList;
    }
    
    //method used to update lead record with its parent lead details from CSV
    @AuraEnabled
    public static List<Lead> readCSVFileToUpdateParentLeads(Id idContentDocument){
        List<Lead> leadList = [Select Id,Name,texcellency__DefHC_HospitalID__c from Lead];
        List<Lead> leadListToUpdate = new List<Lead>();
        
        Set<String> str =  new Set<String>();
        
        Map<Id,Lead> candidateMap = new  Map<Id,Lead>(leadList);
        Map<String,String> leadDefinitiveIdMap = new  Map<String,String>();
        
        if(!leadList.isEmpty()){
            for(Lead leadObj : leadList){
                if(leadObj.texcellency__DefHC_HospitalID__c !=null){
                    str.add(string.valueof(leadObj.texcellency__DefHC_HospitalID__c));
                    leadDefinitiveIdMap.put(string.valueof(leadObj.texcellency__DefHC_HospitalID__c),leadObj.Id);
                }
            }
            system.debug('str:'+str);
            system.debug('leadDefinitiveIdMap:'+leadDefinitiveIdMap);
        }
        
        
        if(idContentDocument != null) {
            system.debug('idContentDocument:'+idContentDocument);
            // getting File Data based on document id 
            ContentVersion objVersion = [SELECT Id, VersionData FROM ContentVersion WHERE ContentDocumentId =:idContentDocument];
            system.debug('objVersions:'+objVersion);
            
            // split the file data
            list<String> lstCSVLines = objVersion.VersionData.toString().split('\n');
            System.debug('lstCSVLines====> '+lstCSVLines);
            
            for(Integer i = 1; i < lstCSVLines.size(); i++){
                Lead leadObj = new Lead();
                Lead parentleadObj = new Lead();
                list<String> csvRowData = lstCSVLines[i].split(',');
                System.debug('csvRowData====> '+csvRowData);
                
                if(str.contains(csvRowData[0])){  
                    if((leadDefinitiveIdMap.get(csvRowData[0]) != null) && (leadDefinitiveIdMap.get(csvRowData[1]) != null)){
                        if(leadDefinitiveIdMap.get(csvRowData[0]) != leadDefinitiveIdMap.get(csvRowData[1])){
                            leadObj.Id = leadDefinitiveIdMap.get(csvRowData[0]);
                            leadObj.Parent_Lead__c = leadDefinitiveIdMap.get(csvRowData[1]);
                            if((leadDefinitiveIdMap.get(csvRowData[1].trim()) != null) && (leadDefinitiveIdMap.get(csvRowData[2].trim()) != null)){
                                if(leadDefinitiveIdMap.get(csvRowData[1].trim()) != leadDefinitiveIdMap.get(csvRowData[2].trim())){
                                    leadObj.Ultimate_Parent_Lead__c = leadDefinitiveIdMap.get(csvRowData[2].trim());
                                }
                            }
                            if(!leadListToUpdate.contains(leadObj)){
                                leadListToUpdate.add(leadObj);
                                
                            }                        
                        }
                        
                    }
                    
                }
            }
        }  
        
        
        try{
            if(!leadListToUpdate.isEmpty()){
                system.debug('leadListToUpdate:'+leadListToUpdate);
                Id batchId = Database.executeBatch(new LeadBatchClass(leadListToUpdate),200);
                system.debug('batch id 1:'+batchId);
                return null;
            }
        }catch (Exception ex) {
            System.debug('error:>>'+ex.getMessage());
            //throw new AuraHandledException(ex.getMessage());
            return null;
        } 
        return Null;
    }

    //method used to update lead record with Definitive data from CSV
    @AuraEnabled
    public static List<Lead> updateLeadsWithDefinitive(Id idContentDocument){
        List<Lead> leadList = [Select Id,Name,texcellency__DefHC_HospitalID__c from Lead];
        List<Lead> leadListToUpdate = new List<Lead>();
        
        Set<String> str =  new Set<String>();
        
        Map<Id,Lead> candidateMap = new  Map<Id,Lead>(leadList);
        Map<String,String> leadDefinitiveIdMap = new  Map<String,String>();
        
        if(!leadList.isEmpty()){
            for(Lead leadObj : leadList){
                if(leadObj.texcellency__DefHC_HospitalID__c !=null){
                    str.add(string.valueof(leadObj.texcellency__DefHC_HospitalID__c));
                    leadDefinitiveIdMap.put(string.valueof(leadObj.texcellency__DefHC_HospitalID__c),leadObj.Id);
                }
            }
            system.debug('str:'+str);
            system.debug('leadDefinitiveIdMap:'+leadDefinitiveIdMap);
        }
        
        
        if(idContentDocument != null) {
            system.debug('idContentDocument:'+idContentDocument);
            // getting File Data based on document id 
            ContentVersion objVersion = [SELECT Id, VersionData FROM ContentVersion WHERE ContentDocumentId =:idContentDocument];
            system.debug('objVersions:'+objVersion);
            
            // split the file data
            list<String> lstCSVLines = objVersion.VersionData.toString().split('\n');
            System.debug('lstCSVLines====> '+lstCSVLines);

            for(Integer i = 1; i < lstCSVLines.size(); i++){
                Lead leadObj = new Lead();
                Lead parentleadObj = new Lead();
                list<String> csvRowData = lstCSVLines[i].split(',');
                System.debug('csvRowData====> '+csvRowData);
                
                if(str.contains(csvRowData[0])){  
                    if(leadDefinitiveIdMap.get(csvRowData[0]) != null){
                        
                        	String genericString;
                            leadObj.Id = leadDefinitiveIdMap.get(csvRowData[0]);
                        	
                            leadObj.DefHC_Hospital_Name__c = csvRowData[1].trim();
                            leadObj.DHC_Provider_Profile__c = csvRowData[2].trim();
                            leadObj.DHC_Provider_Website__c = csvRowData[3].trim();
                            leadObj.DHC_Network_ID__c = csvRowData[4].trim();
                            leadObj.DHC_Network_Name__c = csvRowData[5].trim();
                            leadObj.DHC_Parent_Network_ID__c = csvRowData[6].trim();
                            leadObj.DHC_Parent_Network_Name__c = csvRowData[7].trim();
                        	
                            leadObj.DHC_EMR_Vendor_Ambulatory__c = csvRowData[8].trim();
                        	String s = csvRowData[9].contains('\"')==true ? csvRowData[9].replaceAll('\"', ''):csvRowData[9];
                        	system.debug('csvRowData[9]:'+csvRowData[9]);
                        	system.debug('csvRowData[10]:'+csvRowData[10]);
                            leadObj.DHC_EMR_Vendor_Inpatient__c = s.replaceAll(',', '').trim();
                            leadObj.DHC_of_No_Affiliated_Physicians__c =csvRowData[10] !='' ? Decimal.valueOf(csvRowData[10]) :null;
                            leadObj.DHC_No_of_Beds__c = csvRowData[11] !='' ? Decimal.valueOf(csvRowData[11].replaceAll('\"', '')) :null;
                            leadObj.DHC_No_of_Discharges__c =  csvRowData[12] !='' ?Decimal.valueOf(csvRowData[12]):null;
                            leadObj.DHC_Net_Patient_Revenue__c = csvRowData[13];
                            
                            if(!leadListToUpdate.contains(leadObj)){
                                leadListToUpdate.add(leadObj);
                                
                            }                        
                        }
                        
                    }
                    
                }
            } 
        
        
        try{
            if(!leadListToUpdate.isEmpty()){
                system.debug('leadListToUpdate:'+leadListToUpdate);
                //Id batchId = Database.executeBatch(new LeadBatchClass(leadListToUpdate),200);
                //system.debug('batch id 1:'+batchId);
                return null;
            }
        }catch (Exception ex) {
            System.debug('error:>>'+ex.getMessage());
            //throw new AuraHandledException(ex.getMessage());
            return null;
        } 
        return Null;
    }
    
   
}